; Levelling Program
; Generated by Mike Watts on 2016-01-09
; http://www.subdimension.co.uk


M127

G21 (Metric FTW)
G90 (Absolute Positioning)
M18 (Turn off steppers)
M103 ; extruder off
M104 S225 T0 ; set temperature

M6 T0 (wait for toolhead parts, nozzle, HBP, etc., to reach temperature)

G04 P20000 (Wait for 20 seconds for flow)

M127
M104 S0 T0 (Turn off extruder heater)

M18 (Turn off steppers)

